### ISSUE TITLE
Option --existing-config not working on drupal:site-install

### ISSUE THREAD

**Issue by ghost** [php-taskman/drupal#1]
When trying to install a site with existing config I found that the option does not take effect. Upon closer inspection of https://github.com/boedah/robo-drush I see that there now is a public function that allows to set this parameter: https://github.com/boedah/robo-drush/pull/14/files

I think we should use this function, but I'm having trouble implementing it. For some reason I can not get the --existing-config option to propagate to the command.

**Comment by ghost** [comment]
Found the problem. The function should be called before setting the install profile. I will make a pull request soon to solve this issue.

**Comment by drupol** [comment]
Thanks mate :-)
