### ISSUE TITLE
Make sure that all 0.1.* releases work with PHP 5.6

### ISSUE THREAD

**Issue by donquixote** [php-taskman/drupal#7]
The minimum PHP requirement in all 0.1.* releases is PHP 5.6.
However, in ce23bc7acc the dependency to phptaskman/core was changed from "^0.1.16" to "^0.1.17", which requires a version of phptaskman/core-tasks which requires PHP 7.1.

I think all 0.1.* releases should be made to work with PHP 5.6.
Then the 1.*, or perhaps 0.2.*, can require PHP 7.
But 0.1.* should remain on 5.6 for the legacy projects.

**Comment by donquixote** [comment]
Perhaps this should really be done in the php-taskman/core package.
It should require the 0.1.* instead of 1.* of php-taskman/core-tasks.

**Comment by drupol** [comment]
You're right. I will fix that asap.

**Comment by drupol** [comment]
Fixed: https://github.com/php-taskman/core/releases/tag/0.1.18

Use version 0.1.18.

**Comment by aritomelo** [comment]
By using 0.1.18 a new issue arise.
` ./vendor/bin/taskman drupal:site-setupWatch out! GrumPHP is sniffing your commits!
 [PhpTaskman\Core\Filesystem\Filesystem] _chmod ["build/sites",511,0,true]
 [PhpTaskman\Core\Filesystem\Filesystem] symlink ["../../../../..","build/sites/all/themes/custom/atomium"]
 [CompletionWrapper]    in task PhpTaskman\CoreTasks\Plugin\Task\RunTask 
  Unable to find the taskman binary 
 [CompletionWrapper]  Exit code 1 
Script ./vendor/bin/taskman drupal:site-setup handling the post-update-cmd event returned with error code 1
`
